-   id: sql-formatter-dsi
    name: NodeJS SQL syntax formatter (sql-formatter)
    entry: sql-formatter-dsi
    language: node
    args: ["-i"]
    files: .*\.(sql)$
    additional_dependencies: ['sql-formatter-dsi']
